# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd24406a6647cf154cdb7a128981ae352c0662d6561363b373720010fc2a6ae12d81cfce32ff9e8d08ddbdb068919177a85d0f6031221d617c5ff5b90a5a5990

test:
  secret_key_base: 67cf9daa6736ac9a1acbce64b8ccdb4b478fa211549aea3dab63c50530e80a36d217d6b6ae676420e82096f9a13956c0b30c3fec23eae06703d203a6e75dd640

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
