class Search < ActiveRecord::Base
  validates :query, presence: true
  validates :location, presence: true

  belongs_to :user

  CITIES = {
    'Ann Arbor' => { short: 'aaa', url: 'http://annarbor.craigslist.org' },
    'Fraser Valley' => { short: 'abb', url: 'http://abbotsford.craigslist.ca' },
    'Abilene' => { short: 'abi', url: 'http://abilene.craigslist.org' },
    'Albuquerque' => { short: 'abq', url: 'http://albuquerque.craigslist.org' },
    'Northeast SD' => { short: 'abr', url: 'http://nesd.craigslist.org' },
    'Albany' => { short: 'aby', url: 'http://albanyga.craigslist.org' },
    'Aberdeen' => { short: 'abz', url: 'http://aberdeen.craigslist.co.uk' },
    'Acapulco' => { short: 'aca', url: 'http://acapulco.craigslist.com.mx' },
    'Ghana' => { short: 'acc', url: 'http://accra.craigslist.org' },
    'Ethiopia' => { short: 'add', url: 'http://addisababa.craigslist.org' },
    'Adelaide' => { short: 'adl', url: 'http://adelaide.craigslist.com.au' },
    'Central Louisiana' => { short: 'aex', url: 'http://cenla.craigslist.org' },
    'Malaga' => { short: 'agp', url: 'http://malaga.craigslist.es' },
    'Athens' => { short: 'ahn', url: 'http://athensga.craigslist.org' },
    'Auckland' => { short: 'akl', url: 'http://auckland.craigslist.org' },
    'Albany' => { short: 'alb', url: 'http://albany.craigslist.org' },
    'Alicante' => { short: 'alc', url: 'http://alicante.craigslist.es' },
    'Lehigh Valley' => { short: 'alt', url: 'http://allentown.craigslist.org' },
    'Amarillo' => { short: 'ama', url: 'http://amarillo.craigslist.org' },
    'Ahmedabad' => { short: 'amd', url: 'http://ahmedabad.craigslist.co.in' },
    'Ames' => { short: 'ame', url: 'http://ames.craigslist.org' },
    'Amsterdam / Randstad' => { short: 'ams', url: 'http://amsterdam.craigslist.org' },
    'Gadsden-Anniston' => { short: 'anb', url: 'http://gadsden.craigslist.org' },
    'Anchorage / Mat-Su' => { short: 'anc', url: 'http://anchorage.craigslist.org' },
    'Annapolis' => { short: 'anp', url: 'http://annapolis.craigslist.org' },
    'Altoona-Johnstown' => { short: 'aoo', url: 'http://altoona.craigslist.org' },
    'Appleton-Oshkosh-FDL' => { short: 'app', url: 'http://appleton.craigslist.org' },
    'Asheville' => { short: 'ash', url: 'http://asheville.craigslist.org' },
    'Greece' => { short: 'ath', url: 'http://athens.craigslist.gr' },
    'Atlanta' => { short: 'atl', url: 'http://atlanta.craigslist.org' },
    'Auburn' => { short: 'aub', url: 'http://auburn.craigslist.org' },
    'Augusta' => { short: 'aug', url: 'http://augusta.craigslist.org' },
    'Austin' => { short: 'aus', url: 'http://austin.craigslist.org' },
    'Scranton / Wilkes-Barre' => { short: 'avp', url: 'http://scranton.craigslist.org' },
    'Bakersfield' => { short: 'bak', url: 'http://bakersfield.craigslist.org' },
    'Baltimore' => { short: 'bal', url: 'http://baltimore.craigslist.org' },
    'Barcelona' => { short: 'bar', url: 'http://barcelona.craigslist.es' },
    'Bhubaneswar' => { short: 'bbi', url: 'http://bhubaneswar.craigslist.co.in' },
    'Bacolod' => { short: 'bcd', url: 'http://bacolod.craigslist.com.ph' },
    'Baja California Sur' => { short: 'bcs', url: 'http://bajasur.craigslist.com.mx' },
    'Belleville' => { short: 'bel', url: 'http://belleville.craigslist.ca' },
    'Berlin' => { short: 'ber', url: 'http://berlin.craigslist.de' },
    'Beirut, Lebanon' => { short: 'bey', url: 'http://beirut.craigslist.org' },
    'Brantford-Woodstock' => { short: 'bfd', url: 'http://brantford.craigslist.ca' },
    'Scottsbluff / Panhandle' => { short: 'bff', url: 'http://scottsbluff.craigslist.org' },
    'Iraq' => { short: 'bgd', url: 'http://baghdad.craigslist.org' },
    'Bangladesh' => { short: 'bgl', url: 'http://bangladesh.craigslist.org' },
    'Binghamton' => { short: 'bgm', url: 'http://binghamton.craigslist.org' },
    'Birmingham' => { short: 'bhm', url: 'http://bham.craigslist.org' },
    'Birmingham / West Mids' => { short: 'bhx', url: 'http://birmingham.craigslist.co.uk' },
    'Billings' => { short: 'bil', url: 'http://billings.craigslist.org' },
    'Bilbao' => { short: 'bio', url: 'http://bilbao.craigslist.es' },
    'Bismarck' => { short: 'bis', url: 'http://bismarck.craigslist.org' },
    'Bemidji' => { short: 'bji', url: 'http://bemidji.craigslist.org' },
    'Guanajuato' => { short: 'bjx', url: 'http://guanajuato.craigslist.com.mx' },
    'Thailand' => { short: 'bkk', url: 'http://bangkok.craigslist.co.th' },
    'Belfast' => { short: 'blf', url: 'http://belfast.craigslist.co.uk' },
    'Bologna' => { short: 'blg', url: 'http://bologna.craigslist.it' },
    'Bowling Green' => { short: 'blg', url: 'http://bgky.craigslist.org' },
    'Bellingham' => { short: 'bli', url: 'http://bellingham.craigslist.org' },
    'Bloomington-Normal' => { short: 'bln', url: 'http://bn.craigslist.org' },
    'Bloomington' => { short: 'bmg', url: 'http://bloomington.craigslist.org' },
    'Boone' => { short: 'bnc', url: 'http://boone.craigslist.org' },
    'Bend' => { short: 'bnd', url: 'http://bend.craigslist.org' },
    'Brisbane' => { short: 'bne', url: 'http://brisbane.craigslist.com.au' },
    'Bangalore' => { short: 'bng', url: 'http://bangalore.craigslist.co.in' },
    'Bordeaux' => { short: 'bod', url: 'http://bordeaux.craigslist.org' },
    'Colombia' => { short: 'bog', url: 'http://colombia.craigslist.org' },
    'Boise' => { short: 'boi', url: 'http://boise.craigslist.org' },
    'Boston' => { short: 'bos', url: 'http://boston.craigslist.org' },
    'Boulder' => { short: 'bou', url: 'http://boulder.craigslist.org' },
    'Beaumont / Port Arthur' => { short: 'bpt', url: 'http://beaumont.craigslist.org' },
    'Brainerd' => { short: 'brd', url: 'http://brainerd.craigslist.org' },
    'Brighton' => { short: 'bri', url: 'http://brighton.craigslist.co.uk' },
    'Vermont' => { short: 'brl', url: 'http://burlington.craigslist.org' },
    'Bremen' => { short: 'brm', url: 'http://bremen.craigslist.de' },
    'Bern' => { short: 'brn', url: 'http://bern.craigslist.ch' },
    'Brownsville' => { short: 'bro', url: 'http://brownsville.craigslist.org' },
    'Barrie' => { short: 'brr', url: 'http://barrie.craigslist.ca' },
    'Bristol' => { short: 'brs', url: 'http://bristol.craigslist.co.uk' },
    'Belgium' => { short: 'bru', url: 'http://brussels.craigslist.org' },
    'Brasilia' => { short: 'bsb', url: 'http://brasilia.craigslist.org' },
    'Basel' => { short: 'bsl', url: 'http://basel.craigslist.ch' },
    'Battle Creek' => { short: 'btc', url: 'http://battlecreek.craigslist.org' },
    'Bath' => { short: 'bth', url: 'http://bath.craigslist.co.uk' },
    'Butte' => { short: 'btm', url: 'http://butte.craigslist.org' },
    'Baton Rouge' => { short: 'btr', url: 'http://batonrouge.craigslist.org' },
    'Budapest' => { short: 'bud', url: 'http://budapest.craigslist.org' },
    'Buenos Aires' => { short: 'bue', url: 'http://buenosaires.craigslist.org' },
    'Buffalo' => { short: 'buf', url: 'http://buffalo.craigslist.org' },
    'Romania' => { short: 'buh', url: 'http://bucharest.craigslist.org' },
    'Brunswick' => { short: 'bwk', url: 'http://brunswick.craigslist.org' },
    'Bozeman' => { short: 'bzn', url: 'http://bozeman.craigslist.org' },
    'Columbia' => { short: 'cae', url: 'http://columbia.craigslist.org' },
    'Egypt' => { short: 'cai', url: 'http://cairo.craigslist.org' },
    'Akron / Canton' => { short: 'cak', url: 'http://akroncanton.craigslist.org' },
    'Cambridge, UK' => { short: 'cam', url: 'http://cambridge.craigslist.co.uk' },
    'Guangzhou' => { short: 'can', url: 'http://guangzhou.craigslist.com.cn' },
    'Cape Cod / Islands' => { short: 'cap', url: 'http://capecod.craigslist.org' },
    'Morocco' => { short: 'cas', url: 'http://casablanca.craigslist.org' },
    'Catskills' => { short: 'cat', url: 'http://catskills.craigslist.org' },
    'Southern Illinois' => { short: 'cbd', url: 'http://carbondale.craigslist.org' },
    'Cumberland Valley' => { short: 'cbg', url: 'http://chambersburg.craigslist.org' },
    'Cariboo' => { short: 'cbo', url: 'http://cariboo.craigslist.ca' },
    'Canberra' => { short: 'cbr', url: 'http://canberra.craigslist.com.au' },
    'Venezuela' => { short: 'ccs', url: 'http://caracas.craigslist.org' },
    'Cagayan de Oro' => { short: 'cdo', url: 'http://cdo.craigslist.com.ph' },
    'Cadiz' => { short: 'cdz', url: 'http://cadiz.craigslist.es' },
    'Cebu' => { short: 'ceb', url: 'http://cebu.craigslist.com.ph' },
    'Cedar Rapids' => { short: 'ced', url: 'http://cedarrapids.craigslist.org' },
    'Heartland Florida' => { short: 'cfl', url: 'http://cfl.craigslist.org' },
    'Cologne' => { short: 'cgn', url: 'http://cologne.craigslist.de' },
    'Charlotte' => { short: 'cha', url: 'http://charlotte.craigslist.org' },
    'Chico' => { short: 'chc', url: 'http://chico.craigslist.org' },
    'Chennai (Madras)' => { short: 'che', url: 'http://chennai.craigslist.co.in' },
    'Chihuahua' => { short: 'chh', url: 'http://chihuahua.craigslist.com.mx' },
    'Chicago' => { short: 'chi', url: 'http://chicago.craigslist.org' },
    'Chatham-Kent' => { short: 'chk', url: 'http://chatham.craigslist.ca' },
    'Chillicothe' => { short: 'chl', url: 'http://chillicothe.craigslist.org' },
    'Champaign Urbana' => { short: 'chm', url: 'http://chambana.craigslist.org' },
    'Chautauqua' => { short: 'chq', url: 'http://chautauqua.craigslist.org' },
    'Christchurch' => { short: 'chr', url: 'http://christchurch.craigslist.org' },
    'Charleston' => { short: 'chs', url: 'http://charleston.craigslist.org' },
    'Chattanooga' => { short: 'cht', url: 'http://chattanooga.craigslist.org' },
    'Cincinnati' => { short: 'cin', url: 'http://cincinnati.craigslist.org' },
    'Ciudad Juarez' => { short: 'cjs', url: 'http://juarez.craigslist.com.mx' },
    'Chongqing' => { short: 'ckg', url: 'http://chongqing.craigslist.com.cn' },
    'Clarksville' => { short: 'ckv', url: 'http://clarksville.craigslist.org' },
    'Cleveland' => { short: 'cle', url: 'http://cleveland.craigslist.org' },
    'Calgary' => { short: 'clg', url: 'http://calgary.craigslist.ca' },
    'Central Michigan' => { short: 'cmu', url: 'http://centralmich.craigslist.org' },
    'Comox Valley' => { short: 'cmx', url: 'http://comoxvalley.craigslist.ca' },
    'Belo Horizonte' => { short: 'cnf', url: 'http://belohorizonte.craigslist.org' },
    'Central NJ' => { short: 'cnj', url: 'http://cnj.craigslist.org' },
    'Cairns' => { short: 'cns', url: 'http://cairns.craigslist.com.au' },
    'Kerala' => { short: 'cok', url: 'http://kerala.craigslist.co.in' },
    'Columbus' => { short: 'col', url: 'http://columbus.craigslist.org' },
    'Cookeville' => { short: 'coo', url: 'http://cookeville.craigslist.org' },
    'Copenhagen' => { short: 'cop', url: 'http://copenhagen.craigslist.org' },
    'Oregon Coast' => { short: 'cor', url: 'http://oregoncoast.craigslist.org' },
    'Colorado Springs' => { short: 'cos', url: 'http://cosprings.craigslist.org' },
    'Columbia / Jeff City' => { short: 'cou', url: 'http://columbiamo.craigslist.org' },
    'Coventry' => { short: 'cov', url: 'http://coventry.craigslist.co.uk' },
    'Cape Town' => { short: 'cpt', url: 'http://capetown.craigslist.co.za' },
    'Caribbean Islands' => { short: 'crb', url: 'http://caribbean.craigslist.org' },
    'Costa Rica' => { short: 'cri', url: 'http://costarica.craigslist.org' },
    'Pampanga' => { short: 'crk', url: 'http://pampanga.craigslist.com.ph' },
    'Corpus Christi' => { short: 'crp', url: 'http://corpuschristi.craigslist.org' },
    'Corvallis/Albany' => { short: 'crv', url: 'http://corvallis.craigslist.org' },
    'Charleston' => { short: 'crw', url: 'http://charlestonwv.craigslist.org' },
    'Pierre / Central SD' => { short: 'csd', url: 'http://csd.craigslist.org' },
    'Columbus' => { short: 'csg', url: 'http://columbusga.craigslist.org' },
    'College Station' => { short: 'cst', url: 'http://collegestation.craigslist.org' },
    'Chengdu' => { short: 'ctu', url: 'http://chengdu.craigslist.com.cn' },
    'Clovis / Portales' => { short: 'cvn', url: 'http://clovis.craigslist.org' },
    'Curitiba' => { short: 'cwb', url: 'http://curitiba.craigslist.org' },
    'Cardiff / Wales' => { short: 'cym', url: 'http://cardiff.craigslist.co.uk' },
    'Daytona Beach' => { short: 'dab', url: 'http://daytona.craigslist.org' },
    'Dallas / Fort Worth' => { short: 'dal', url: 'http://dallas.craigslist.org' },
    'Dayton / Springfield' => { short: 'day', url: 'http://dayton.craigslist.org' },
    'Dubuque' => { short: 'dbq', url: 'http://dubuque.craigslist.org' },
    'Derby' => { short: 'dby', url: 'http://derby.craigslist.co.uk' },
    'Delhi' => { short: 'del', url: 'http://delhi.craigslist.co.in' },
    'Denver' => { short: 'den', url: 'http://denver.craigslist.org' },
    'Detroit Metro' => { short: 'det', url: 'http://detroit.craigslist.org' },
    'Dothan' => { short: 'dhn', url: 'http://dothan.craigslist.org' },
    'Decatur' => { short: 'dil', url: 'http://decatur.craigslist.org' },
    'Dalian' => { short: 'dlc', url: 'http://dalian.craigslist.com.cn' },
    'Duluth / Superior' => { short: 'dlh', url: 'http://duluth.craigslist.org' },
    'Delaware' => { short: 'dlw', url: 'http://delaware.craigslist.org' },
    'Dundee' => { short: 'dnd', url: 'http://dundee.craigslist.co.uk' },
    'Danville' => { short: 'dnv', url: 'http://danville.craigslist.org' },
    'Dresden' => { short: 'drs', url: 'http://dresden.craigslist.de' },
    'Del Rio / Eagle Pass' => { short: 'drt', url: 'http://delrio.craigslist.org' },
    'Darwin' => { short: 'drw', url: 'http://darwin.craigslist.com.au' },
    'Des Moines' => { short: 'dsm', url: 'http://desmoines.craigslist.org' },
    'Dublin' => { short: 'dub', url: 'http://dublin.craigslist.org' },
    'Dunedin' => { short: 'dud', url: 'http://dunedin.craigslist.co.nz' },
    'Durban' => { short: 'dur', url: 'http://durban.craigslist.co.za' },
    'Dusseldorf' => { short: 'dus', url: 'http://dusseldorf.craigslist.de' },
    'Devon & Cornwall' => { short: 'dvc', url: 'http://devon.craigslist.co.uk' },
    'Davao City' => { short: 'dvo', url: 'http://davaocity.craigslist.com.ph' },
    'Eau Claire' => { short: 'eau', url: 'http://eauclaire.craigslist.org' },
    'Eastern CO' => { short: 'eco', url: 'http://eastco.craigslist.org' },
    'Edinburgh' => { short: 'edi', url: 'http://edinburgh.craigslist.co.uk' },
    'Edmonton' => { short: 'edm', url: 'http://edmonton.craigslist.ca' },
    'East Idaho' => { short: 'eid', url: 'http://eastidaho.craigslist.org' },
    'Eastern Kentucky' => { short: 'eky', url: 'http://eastky.craigslist.org' },
    'Elko' => { short: 'elk', url: 'http://elko.craigslist.org' },
    'Elmira-Corning' => { short: 'elm', url: 'http://elmira.craigslist.org' },
    'El Paso' => { short: 'elp', url: 'http://elpaso.craigslist.org' },
    'East Midlands' => { short: 'eml', url: 'http://eastmids.craigslist.co.uk' },
    'Kenai Peninsula' => { short: 'ena', url: 'http://kenai.craigslist.org' },
    'Eastern NC' => { short: 'enc', url: 'http://eastnc.craigslist.org' },
    'Northwest OK' => { short: 'end', url: 'http://enid.craigslist.org' },
    'East Oregon' => { short: 'eor', url: 'http://eastoregon.craigslist.org' },
    'Erie' => { short: 'eri', url: 'http://erie.craigslist.org' },
    'Eastern Shore' => { short: 'esh', url: 'http://easternshore.craigslist.org' },
    'Essen / Ruhr' => { short: 'ess', url: 'http://essen.craigslist.de' },
    'Essex' => { short: 'esx', url: 'http://essex.craigslist.co.uk' },
    'Tyler / East TX' => { short: 'etx', url: 'http://easttexas.craigslist.org' },
    'Eugene' => { short: 'eug', url: 'http://eugene.craigslist.org' },
    'Evansville' => { short: 'ew', url: 'http://evansville.craigslist.org' },
    'Eastern Panhandle' => { short: 'ewv', url: 'http://martinsburg.craigslist.org' },
    'Fredericksburg' => { short: 'ezf', url: 'http://fredericksburg.craigslist.org' },
    'Fairbanks' => { short: 'fai', url: 'http://fairbanks.craigslist.org' },
    'Fargo / Moorhead' => { short: 'far', url: 'http://fargo.craigslist.org' },
    'Fayetteville' => { short: 'fay', url: 'http://fayetteville.craigslist.org' },
    'Kalispell' => { short: 'fca', url: 'http://kalispell.craigslist.org' },
    'Frederick' => { short: 'fdk', url: 'http://frederick.craigslist.org' },
    'Finger Lakes' => { short: 'fgl', url: 'http://fingerlakes.craigslist.org' },
    'Sierra Vista' => { short: 'fhu', url: 'http://sierravista.craigslist.org' },
    'Flagstaff / Sedona' => { short: 'flg', url: 'http://flagstaff.craigslist.org' },
    'Florence' => { short: 'flo', url: 'http://florencesc.craigslist.org' },
    'Florence / Tuscany' => { short: 'flr', url: 'http://florence.craigslist.it' },
    'Ft mcmurray' => { short: 'fmc', url: 'http://ftmcmurray.craigslist.ca' },
    'Ft myers / SW Florida' => { short: 'fmy', url: 'http://fortmyers.craigslist.org' },
    'Farmington' => { short: 'fnm', url: 'http://farmington.craigslist.org' },
    'Flint' => { short: 'fnt', url: 'http://flint.craigslist.org' },
    'Frankfurt' => { short: 'fra', url: 'http://frankfurt.craigslist.de' },
    'Fresno / Madera' => { short: 'fre', url: 'http://fresno.craigslist.org' },
    'Faro / Algarve' => { short: 'fro', url: 'http://faro.craigslist.pt' },
    'Sioux falls / SE SD' => { short: 'fsd', url: 'http://siouxfalls.craigslist.org' },
    'Fort Smith' => { short: 'fsm', url: 'http://fortsmith.craigslist.org' },
    'Fort Collins / North CO' => { short: 'ftc', url: 'http://fortcollins.craigslist.org' },
    'Fort Dodge' => { short: 'ftd', url: 'http://fortdodge.craigslist.org' },
    'Fortaleza' => { short: 'ftl', url: 'http://fortaleza.craigslist.org' },
    'Fukuoka' => { short: 'fuk', url: 'http://fukuoka.craigslist.jp' },
    'Fort Wayne' => { short: 'fwa', url: 'http://fortwayne.craigslist.org' },
    'Fayetteville' => { short: 'fyv', url: 'http://fayar.craigslist.org' },
    'Greensboro' => { short: 'gbo', url: 'http://greensboro.craigslist.org' },
    'Guadalajara' => { short: 'gdl', url: 'http://guadalajara.craigslist.com.mx' },
    'Genoa' => { short: 'gen', url: 'http://genoa.craigslist.it' },
    'Grand Forks' => { short: 'gfk', url: 'http://grandforks.craigslist.org' },
    'Glens Falls' => { short: 'gfl', url: 'http://glensfalls.craigslist.org' },
    'Grand Island' => { short: 'gil', url: 'http://grandisland.craigslist.org' },
    'Western Slope' => { short: 'gjt', url: 'http://westslope.craigslist.org' },
    'Glasgow' => { short: 'gla', url: 'http://glasgow.craigslist.co.uk' },
    'Gold Country' => { short: 'gld', url: 'http://goldcountry.craigslist.org' },
    'Galveston' => { short: 'gls', url: 'http://galveston.craigslist.org' },
    'Grenoble' => { short: 'gnb', url: 'http://grenoble.craigslist.org' },
    'Gainesville' => { short: 'gnv', url: 'http://gainesville.craigslist.org' },
    'Goa' => { short: 'goa', url: 'http://goa.craigslist.co.in' },
    'Guelph' => { short: 'gph', url: 'http://guelph.craigslist.ca' },
    'Gulfport / Biloxi' => { short: 'gpt', url: 'http://gulfport.craigslist.org' },
    'Green bay' => { short: 'grb', url: 'http://greenbay.craigslist.org' },
    'Killeen / Temple / Ft Hood' => { short: 'grk', url: 'http://killeen.craigslist.org' },
    'Grand Rapids' => { short: 'grr', url: 'http://grandrapids.craigslist.org' },
    'Granada' => { short: 'grx', url: 'http://granada.craigslist.es' },
    'Greenville / Upstate' => { short: 'gsp', url: 'http://greenville.craigslist.org' },
    'Great Falls' => { short: 'gtf', url: 'http://greatfalls.craigslist.org' },
    'Guatemala' => { short: 'gua', url: 'http://guatemala.craigslist.org' },
    'Guam-Micronesia' => { short: 'gum', url: 'http://micronesia.craigslist.org' },
    'Geneva' => { short: 'gva', url: 'http://geneva.craigslist.ch' },
    'Hannover' => { short: 'haj', url: 'http://hannover.craigslist.de' },
    'Hamburg' => { short: 'ham', url: 'http://hamburg.craigslist.de' },
    'Medicine Hat' => { short: 'hat', url: 'http://hat.craigslist.ca' },
    'Tasmania' => { short: 'hba', url: 'http://hobart.craigslist.com.au' },
    'Heidelberg' => { short: 'hdb', url: 'http://heidelberg.craigslist.de' },
    'Finland' => { short: 'hel', url: 'http://helsinki.craigslist.fi' },
    'Southwest MS' => { short: 'hez', url: 'http://natchez.craigslist.org' },
    'Haifa' => { short: 'hfa', url: 'http://haifa.craigslist.org' },
    'Halifax' => { short: 'hfx', url: 'http://halifax.craigslist.ca' },
    'Hangzhou' => { short: 'hgh', url: 'http://hangzhou.craigslist.com.cn' },
    'Hilton head' => { short: 'hhi', url: 'http://hiltonhead.craigslist.org' },
    'Hiroshima' => { short: 'hij', url: 'http://hiroshima.craigslist.jp' },
    'Hickory / Lenoir' => { short: 'hky', url: 'http://hickory.craigslist.org' },
    'Hong Kong' => { short: 'hkz', url: 'http://hongkong.craigslist.hk' },
    'Holland' => { short: 'hld', url: 'http://holland.craigslist.org' },
    'Helena' => { short: 'hln', url: 'http://helena.craigslist.org' },
    'Humboldt County' => { short: 'hmb', url: 'http://humboldt.craigslist.org' },
    'Hamilton-Burlington' => { short: 'hml', url: 'http://hamilton.craigslist.ca' },
    'Hanford-Corcoran' => { short: 'hnf', url: 'http://hanford.craigslist.org' },
    'Hawaii' => { short: 'hnl', url: 'http://honolulu.craigslist.org' },
    'Houston' => { short: 'hou', url: 'http://houston.craigslist.org' },
    'Pretoria' => { short: 'hpr', url: 'http://pretoria.craigslist.co.za' },
    'Hermosillo' => { short: 'hrm', url: 'http://hermosillo.craigslist.com.mx' },
    'Harrisburg' => { short: 'hrs', url: 'http://harrisburg.craigslist.org' },
    'Huntsville / Decatur' => { short: 'hsv', url: 'http://huntsville.craigslist.org' },
    'Hartford' => { short: 'htf', url: 'http://hartford.craigslist.org' },
    'Huntington-Ashland' => { short: 'hts', url: 'http://huntington.craigslist.org' },
    'Hudson Valley' => { short: 'hud', url: 'http://hudsonvalley.craigslist.org' },
    'Houma' => { short: 'hum', url: 'http://houma.craigslist.org' },
    'New Haven' => { short: 'hvn', url: 'http://newhaven.craigslist.org' },
    'Hyderabad' => { short: 'hyd', url: 'http://hyderabad.craigslist.co.in' },
    'Iowa City' => { short: 'iac', url: 'http://iowacity.craigslist.org' },
    'Baleares' => { short: 'ibz', url: 'http://baleares.craigslist.es' },
    'Indore' => { short: 'idr', url: 'http://indore.craigslist.co.in' },
    'Iloilo' => { short: 'ilo', url: 'http://iloilo.craigslist.com.ph' },
    'Imperial County' => { short: 'imp', url: 'http://imperial.craigslist.org' },
    'Indianapolis' => { short: 'ind', url: 'http://indianapolis.craigslist.org' },
    'Inland Empire' => { short: 'inl', url: 'http://inlandempire.craigslist.org' },
    'Long Island' => { short: 'isp', url: 'http://longisland.craigslist.org' },
    'Turkey' => { short: 'ist', url: 'http://istanbul.craigslist.com.tr' },
    'Ithaca' => { short: 'ith', url: 'http://ithaca.craigslist.org' },
    'Chandigarh' => { short: 'ixc', url: 'http://chandigarh.craigslist.co.in' },
    'Jaipur' => { short: 'jai', url: 'http://jaipur.craigslist.co.in' },
    'Jackson' => { short: 'jan', url: 'http://jackson.craigslist.org' },
    'Jacksonville' => { short: 'jax', url: 'http://jacksonville.craigslist.org' },
    'Jonesboro' => { short: 'jbr', url: 'http://jonesboro.craigslist.org' },
    'Ashtabula' => { short: 'jfn', url: 'http://ashtabula.craigslist.org' },
    'Indonesia' => { short: 'jkt', url: 'http://jakarta.craigslist.org' },
    'Joplin' => { short: 'jln', url: 'http://joplin.craigslist.org' },
    'Johannesburg' => { short: 'jnb', url: 'http://johannesburg.craigslist.co.za' },
    'Southeast Alaska' => { short: 'jnu', url: 'http://juneau.craigslist.org' },
    'Jerusalem' => { short: 'jrs', url: 'http://jerusalem.craigslist.org' },
    'Janesville' => { short: 'jvl', url: 'http://janesville.craigslist.org' },
    'Jackson' => { short: 'jxn', url: 'http://jxn.craigslist.org' },
    'Jackson ' => { short: 'jxt', url: 'http://jacksontn.craigslist.org' },
    'Jersey Shore' => { short: 'jys', url: 'http://jerseyshore.craigslist.org' },
    'Ukraine' => { short: 'kbp', url: 'http://ukraine.craigslist.org' },
    'Kitchener-Waterloo-Cambridge' => { short: 'kch', url: 'http://kitchener.craigslist.ca' },
    'Kelowna / Okanagan' => { short: 'kel', url: 'http://kelowna.craigslist.ca' },
    'Kent' => { short: 'ken', url: 'http://kent.craigslist.co.uk' },
    'Florida Keys' => { short: 'key', url: 'http://keys.craigslist.org' },
    'Klamath Falls' => { short: 'klf', url: 'http://klamath.craigslist.org' },
    'Kaiserslautern' => { short: 'klt', url: 'http://kaiserslautern.craigslist.de' },
    'Kamloops' => { short: 'kml', url: 'http://kamloops.craigslist.ca' },
    'Kingston' => { short: 'kng', url: 'http://kingston.craigslist.ca' },
    'Knoxville' => { short: 'knx', url: 'http://knoxville.craigslist.org' },
    'Kolkata (Calcutta)' => { short: 'kol', url: 'http://kolkata.craigslist.co.in' },
    'Kootenays' => { short: 'koo', url: 'http://cranbrook.craigslist.ca' },
    'Kennewick-Pasco-Richland' => { short: 'kpr', url: 'http://kpr.craigslist.org' },
    'Kirksville' => { short: 'krk', url: 'http://kirksville.craigslist.org' },
    'Kansas City' => { short: 'ksc', url: 'http://kansascity.craigslist.org' },
    'Kuwait' => { short: 'kwi', url: 'http://kuwait.craigslist.org' },
    'Kalamazoo' => { short: 'kzo', url: 'http://kalamazoo.craigslist.org' },
    'Lafayette / West Lafayette' => { short: 'laf', url: 'http://tippecanoe.craigslist.org' },
    'Lakeland' => { short: 'lal', url: 'http://lakeland.craigslist.org' },
    'Lansing' => { short: 'lan', url: 'http://lansing.craigslist.org' },
    'Lausanne' => { short: 'lau', url: 'http://lausanne.craigslist.ch' },
    'Lawton' => { short: 'law', url: 'http://lawton.craigslist.org' },
    'Los Angeles' => { short: 'lax', url: 'http://losangeles.craigslist.org' },
    'Lubbock' => { short: 'lbb', url: 'http://lubbock.craigslist.org' },
    'North Platte' => { short: 'lbf', url: 'http://northplatte.craigslist.org' },
    'North Central FL' => { short: 'lcq', url: 'http://lakecity.craigslist.org' },
    'Las Cruces' => { short: 'lcr', url: 'http://lascruces.craigslist.org' },
    'London' => { short: 'ldn', url: 'http://london.craigslist.co.uk' },
    'Leeds' => { short: 'lds', url: 'http://leeds.craigslist.co.uk' },
    'Leipzig' => { short: 'lej', url: 'http://leipzig.craigslist.de' },
    'Lexington' => { short: 'lex', url: 'http://lexington.craigslist.org' },
    'Lafayette' => { short: 'lft', url: 'http://lafayette.craigslist.org' },
    'Logan' => { short: 'lgu', url: 'http://logan.craigslist.org' },
    'Lille' => { short: 'lil', url: 'http://lille.craigslist.org' },
    'Peru' => { short: 'lim', url: 'http://lima.craigslist.org' },
    'Lisbon' => { short: 'lis', url: 'http://lisbon.craigslist.pt' },
    'Little Rock' => { short: 'lit', url: 'http://littlerock.craigslist.org' },
    'Liverpool' => { short: 'liv', url: 'http://liverpool.craigslist.co.uk' },
    'Lake Charles' => { short: 'lkc', url: 'http://lakecharles.craigslist.org' },
    'Lucknow' => { short: 'lko', url: 'http://lucknow.craigslist.co.in' },
    'Lima / Findlay' => { short: 'lma', url: 'http://limaohio.craigslist.org' },
    'Lincoln' => { short: 'lnk', url: 'http://lincoln.craigslist.org' },
    'Lancaster' => { short: 'lns', url: 'http://lancaster.craigslist.org' },
    'London' => { short: 'lon', url: 'http://londonon.craigslist.ca' },
    'Louisville' => { short: 'lou', url: 'http://louisville.craigslist.org' },
    'Lake of the Ozarks' => { short: 'loz', url: 'http://loz.craigslist.org' },
    'Bolivia' => { short: 'lpb', url: 'http://lapaz.craigslist.org' },
    'Laredo' => { short: 'lrd', url: 'http://laredo.craigslist.org' },
    'La Crosse' => { short: 'lse', url: 'http://lacrosse.craigslist.org' },
    'La Salle CO' => { short: 'lsl', url: 'http://lasalle.craigslist.org' },
    'Lethbridge' => { short: 'lth', url: 'http://lethbridge.craigslist.ca' },
    'Luxembourg' => { short: 'lux', url: 'http://luxembourg.craigslist.org' },
    'Las Vegas' => { short: 'lvg', url: 'http://lasvegas.craigslist.org' },
    'Lawrence' => { short: 'lwr', url: 'http://lawrence.craigslist.org' },
    'Lewiston / Clarkston' => { short: 'lws', url: 'http://lewiston.craigslist.org' },
    'Lynchburg' => { short: 'lyn', url: 'http://lynchburg.craigslist.org' },
    'Lyon' => { short: 'lys', url: 'http://lyon.craigslist.org' },
    'Madison' => { short: 'mad', url: 'http://madison.craigslist.org' },
    'Manchester' => { short: 'man', url: 'http://manchester.craigslist.co.uk' },
    'Saginaw-Midland-Baycity' => { short: 'mbs', url: 'http://saginaw.craigslist.org' },
    'Mcallen / Edinburg' => { short: 'mca', url: 'http://mcallen.craigslist.org' },
    'Macon / Warner Robins' => { short: 'mcn', url: 'http://macon.craigslist.org' },
    'Madrid' => { short: 'mdd', url: 'http://madrid.craigslist.es' },
    'Mendocino County' => { short: 'mdo', url: 'http://mendocino.craigslist.org' },
    'Meadville' => { short: 'mdv', url: 'http://meadville.craigslist.org' },
    'Meridian' => { short: 'mei', url: 'http://meridian.craigslist.org' },
    'Melbourne' => { short: 'mel', url: 'http://melbourne.craigslist.com.au' },
    'Memphis' => { short: 'mem', url: 'http://memphis.craigslist.org' },
    'Merced' => { short: 'mer', url: 'http://merced.craigslist.org' },
    'Mexico City' => { short: 'mex', url: 'http://mexicocity.craigslist.com.mx' },
    'Mansfield' => { short: 'mfd', url: 'http://mansfield.craigslist.org' },
    'Medford-Ashland' => { short: 'mfr', url: 'http://medford.craigslist.org' },
    'Nicaragua' => { short: 'mga', url: 'http://managua.craigslist.org' },
    'Montgomery' => { short: 'mgm', url: 'http://montgomery.craigslist.org' },
    'Manhattan' => { short: 'mhk', url: 'http://ksu.craigslist.org' },
    'Mohave County' => { short: 'mhv', url: 'http://mohave.craigslist.org' },
    'Fort Lauderdale' => { short: 'mia', url: 'http://fortlauderdale.craigslist.org' },
    'South Florida' => { short: 'mia', url: 'http://miami.craigslist.org' },
    'West Palm Beach' => { short: 'mia', url: 'http://westpalmbeach.craigslist.org' },
    'Milwaukee' => { short: 'mil', url: 'http://milwaukee.craigslist.org' },
    'Minneapolis / St Paul' => { short: 'min', url: 'http://minneapolis.craigslist.org' },
    'Muskegon' => { short: 'mkg', url: 'http://muskegon.craigslist.org' },
    'Mankato' => { short: 'mkt', url: 'http://mankato.craigslist.org' },
    'Space Coast' => { short: 'mlb', url: 'http://spacecoast.craigslist.org' },
    'Quad Cities' => { short: 'mli', url: 'http://quadcities.craigslist.org' },
    'Moses Lake' => { short: 'mlk', url: 'http://moseslake.craigslist.org' },
    'Monroe' => { short: 'mlu', url: 'http://monroemi.craigslist.org' },
    'Malaysia' => { short: 'mly', url: 'http://malaysia.craigslist.org' },
    'Southwest MN' => { short: 'mml', url: 'http://marshall.craigslist.org' },
    'Maine' => { short: 'mne', url: 'http://maine.craigslist.org' },
    'Manila' => { short: 'mnl', url: 'http://manila.craigslist.com.ph' },
    'Monroe' => { short: 'mnr', url: 'http://monroe.craigslist.org' },
    'Montana (Old)' => { short: 'mnt', url: 'http://montana.craigslist.org' },
    'Mobile' => { short: 'mob', url: 'http://mobile.craigslist.org' },
    'Modesto' => { short: 'mod', url: 'http://modesto.craigslist.org' },
    'Montreal' => { short: 'mon', url: 'http://montreal.craigslist.ca' },
    'Moscow' => { short: 'mos', url: 'http://moscow.craigslist.org' },
    'Montpellier' => { short: 'mpl', url: 'http://montpellier.craigslist.org' },
    'Marseille' => { short: 'mrs', url: 'http://marseilles.craigslist.org' },
    'Mason city' => { short: 'msc', url: 'http://masoncity.craigslist.org' },
    'Florence / Muscle Shoals' => { short: 'msl', url: 'http://shoals.craigslist.org' },
    'Missoula' => { short: 'mso', url: 'http://missoula.craigslist.org' },
    'Monterey Bay' => { short: 'mtb', url: 'http://monterey.craigslist.org' },
    'Mattoon-Charleston' => { short: 'mto', url: 'http://mattoon.craigslist.org' },
    'Monterrey' => { short: 'mty', url: 'http://monterrey.craigslist.com.mx' },
    'Munich' => { short: 'muc', url: 'http://munich.craigslist.de' },
    'Mumbai' => { short: 'mum', url: 'http://mumbai.craigslist.co.in' },
    'Muncie / Anderson' => { short: 'mun', url: 'http://muncie.craigslist.org' },
    'Montevideo' => { short: 'mvd', url: 'http://montevideo.craigslist.org' },
    'Skagit / Island / SJI' => { short: 'mvw', url: 'http://skagit.craigslist.org' },
    'Milan' => { short: 'mxp', url: 'http://milan.craigslist.it' },
    'Myrtle Beach' => { short: 'myr', url: 'http://myrtlebeach.craigslist.org' },
    'Mazatlan' => { short: 'mzt', url: 'http://mazatlan.craigslist.com.mx' },
    'Napoli / Campania' => { short: 'nap', url: 'http://naples.craigslist.it' },
    'Kenya' => { short: 'nbo', url: 'http://kenya.craigslist.org' },
    'New Brunswick' => { short: 'nbw', url: 'http://newbrunswick.craigslist.ca' },
    'Nice / Cote d\'Azur' => { short: 'nce', url: 'http://cotedazur.craigslist.org' },
    'Newcastle / NE England' => { short: 'ncl', url: 'http://newcastle.craigslist.co.uk' },
    'Northwest CT' => { short: 'nct', url: 'http://nwct.craigslist.org' },
    'North Dakota' => { short: 'ndk', url: 'http://nd.craigslist.org' },
    'Hampton Roads' => { short: 'nfk', url: 'http://norfolk.craigslist.org' },
    'St John\'s' => { short: 'nfl', url: 'http://newfoundland.craigslist.ca' },
    'Nagoya' => { short: 'ngo', url: 'http://nagoya.craigslist.jp' },
    'New Hampshire' => { short: 'nhm', url: 'http://nh.craigslist.org' },
    'North Jersey' => { short: 'njy', url: 'http://newjersey.craigslist.org' },
    'Nanjing' => { short: 'nkg', url: 'http://nanjing.craigslist.com.cn' },
    'Eastern CT' => { short: 'nlo', url: 'http://newlondon.craigslist.org' },
    'Northern Michigan' => { short: 'nmi', url: 'http://nmi.craigslist.org' },
    'Nanaimo' => { short: 'nmo', url: 'http://nanaimo.craigslist.ca' },
    'North Mississippi' => { short: 'nms', url: 'http://northmiss.craigslist.org' },
    'New Orleans' => { short: 'nor', url: 'http://neworleans.craigslist.org' },
    'Nottingham' => { short: 'not', url: 'http://nottingham.craigslist.co.uk' },
    'Tuscarawas CO' => { short: 'nph', url: 'http://tuscarawas.craigslist.org' },
    'Niagara Region' => { short: 'nsc', url: 'http://niagara.craigslist.ca' },
    'Nashville' => { short: 'nsh', url: 'http://nashville.craigslist.org' },
    'Loire Valley' => { short: 'nte', url: 'http://loire.craigslist.org' },
    'Newcastle, NSW' => { short: 'ntl', url: 'http://ntl.craigslist.com.au' },
    'Nuremberg' => { short: 'nue', url: 'http://nuremberg.craigslist.de' },
    'Northwest GA' => { short: 'nwg', url: 'http://nwga.craigslist.org' },
    'East Anglia' => { short: 'nwh', url: 'http://norwich.craigslist.co.uk' },
    'Northern WI' => { short: 'nwi', url: 'http://northernwi.craigslist.org' },
    'Northwest KS' => { short: 'nwk', url: 'http://nwks.craigslist.org' },
    'New York City' => { short: 'nyc', url: 'http://newyork.craigslist.org' },
    'Jacksonville' => { short: 'oaj', url: 'http://onslow.craigslist.org' },
    'Oaxaca' => { short: 'oax', url: 'http://oaxaca.craigslist.com.mx' },
    'Outer Banks' => { short: 'obx', url: 'http://outerbanks.craigslist.org' },
    'Ocala' => { short: 'oca', url: 'http://ocala.craigslist.org' },
    'Deep East Texas' => { short: 'och', url: 'http://nacogdoches.craigslist.org' },
    'Odessa / Midland' => { short: 'odm', url: 'http://odessa.craigslist.org' },
    'Ogden-Clearfield' => { short: 'ogd', url: 'http://ogden.craigslist.org' },
    'Athens' => { short: 'ohu', url: 'http://athensohio.craigslist.org' },
    'Okinawa' => { short: 'oka', url: 'http://okinawa.craigslist.jp' },
    'Oklahoma City' => { short: 'okc', url: 'http://oklahomacity.craigslist.org' },
    'Kokomo' => { short: 'okk', url: 'http://kokomo.craigslist.org' },
    'Winchester' => { short: 'okv', url: 'http://winchester.craigslist.org' },
    'Olympic Peninsula' => { short: 'olp', url: 'http://olympic.craigslist.org' },
    'Omaha / Council Bluffs' => { short: 'oma', url: 'http://omaha.craigslist.org' },
    'Oneonta' => { short: 'onh', url: 'http://oneonta.craigslist.org' },
    'Gold Coast' => { short: 'ool', url: 'http://goldcoast.craigslist.com.au' },
    'Orange County' => { short: 'orc', url: 'http://orangecounty.craigslist.org' },
    'Orlando' => { short: 'orl', url: 'http://orlando.craigslist.org' },
    'Osaka-Kobe-Kyoto' => { short: 'osa', url: 'http://osaka.craigslist.jp' },
    'Norway' => { short: 'osl', url: 'http://oslo.craigslist.org' },
    'Stillwater' => { short: 'osu', url: 'http://stillwater.craigslist.org' },
    'Ottawa-Hull-Gatineau' => { short: 'ott', url: 'http://ottawa.craigslist.ca' },
    'Southeast IA' => { short: 'otu', url: 'http://ottumwa.craigslist.org' },
    'Oxford' => { short: 'ovf', url: 'http://oxford.craigslist.co.uk' },
    'Owensboro' => { short: 'owb', url: 'http://owensboro.craigslist.org' },
    'Owen Sound' => { short: 'ows', url: 'http://owensound.craigslist.ca' },
    'Ventura County' => { short: 'oxr', url: 'http://ventura.craigslist.org' },
    'Pakistan' => { short: 'pak', url: 'http://pakistan.craigslist.org' },
    'West Bank' => { short: 'pal', url: 'http://ramallah.craigslist.org' },
    'Panama' => { short: 'pan', url: 'http://panama.craigslist.org' },
    'Paris' => { short: 'par', url: 'http://paris.craigslist.org' },
    'Peace River Country' => { short: 'pax', url: 'http://peace.craigslist.ca' },
    'Puebla' => { short: 'pbl', url: 'http://puebla.craigslist.com.mx' },
    'Portland' => { short: 'pdx', url: 'http://portland.craigslist.org' },
    'Perugia' => { short: 'peg', url: 'http://perugia.craigslist.it' },
    'Prince Edward Island' => { short: 'pei', url: 'http://pei.craigslist.ca' },
    'Beijing' => { short: 'pek', url: 'http://beijing.craigslist.com.cn' },
    'Perth' => { short: 'per', url: 'http://perth.craigslist.com.au' },
    'Panama City' => { short: 'pfn', url: 'http://panamacity.craigslist.org' },
    'Porto Alegre' => { short: 'pgp', url: 'http://portoalegre.craigslist.org' },
    'Philadelphia' => { short: 'phi', url: 'http://philadelphia.craigslist.org' },
    'Port Huron' => { short: 'phn', url: 'http://porthuron.craigslist.org' },
    'Phoenix' => { short: 'phx', url: 'http://phoenix.craigslist.org' },
    'Peoria' => { short: 'pia', url: 'http://peoria.craigslist.org' },
    'Pittsburgh' => { short: 'pit', url: 'http://pittsburgh.craigslist.org' },
    'Parkersburg-Marietta' => { short: 'pkb', url: 'http://parkersburg.craigslist.org' },
    'Plattsburgh-Adirondacks' => { short: 'plb', url: 'http://plattsburgh.craigslist.org' },
    'Pullman / Moscow' => { short: 'plm', url: 'http://pullman.craigslist.org' },
    'Pune' => { short: 'png', url: 'http://pune.craigslist.co.in' },
    'Pensacola' => { short: 'pns', url: 'http://pensacola.craigslist.org' },
    'Poconos' => { short: 'poc', url: 'http://poconos.craigslist.org' },
    'Prescott' => { short: 'prc', url: 'http://prescott.craigslist.org' },
    'Prague' => { short: 'prg', url: 'http://prague.craigslist.cz' },
    'Puerto Rico' => { short: 'pri', url: 'http://puertorico.craigslist.org' },
    'Rhode Island' => { short: 'prv', url: 'http://providence.craigslist.org' },
    'Treasure Coast' => { short: 'psl', url: 'http://treasure.craigslist.org' },
    'Palm Springs' => { short: 'psp', url: 'http://palmsprings.craigslist.org' },
    'State College' => { short: 'psu', url: 'http://pennstate.craigslist.org' },
    'Potsdam-Canton-Massena' => { short: 'ptd', url: 'http://potsdam.craigslist.org' },
    'Porto' => { short: 'pto', url: 'http://porto.craigslist.pt' },
    'Pueblo' => { short: 'pub', url: 'http://pueblo.craigslist.org' },
    'Puerto Vallarta' => { short: 'pvr', url: 'http://pv.craigslist.com.mx' },
    'Provo / Orem' => { short: 'pvu', url: 'http://provo.craigslist.org' },
    'Quebec City' => { short: 'qbc', url: 'http://quebec.craigslist.ca' },
    'Western IL' => { short: 'qcy', url: 'http://quincy.craigslist.org' },
    'Ecuador' => { short: 'qui', url: 'http://quito.craigslist.org' },
    'Kenosha-Racine' => { short: 'rac', url: 'http://racine.craigslist.org' },
    'Raleigh / Durham / CH' => { short: 'ral', url: 'http://raleigh.craigslist.org' },
    'Rapid City / West SD' => { short: 'rap', url: 'http://rapidcity.craigslist.org' },
    'Roseburg' => { short: 'rbg', url: 'http://roseburg.craigslist.org' },
    'High Rockies' => { short: 'rck', url: 'http://rockies.craigslist.org' },
    'Rochester' => { short: 'rcs', url: 'http://rochester.craigslist.org' },
    'Redding' => { short: 'rdd', url: 'http://redding.craigslist.org' },
    'Reading' => { short: 'rea', url: 'http://reading.craigslist.org' },
    'Recife' => { short: 'rec', url: 'http://recife.craigslist.org' },
    'Red Deer' => { short: 'red', url: 'http://reddeer.craigslist.ca' },
    'Regina' => { short: 'reg', url: 'http://regina.craigslist.ca' },
    'Rockford' => { short: 'rfd', url: 'http://rockford.craigslist.org' },
    'Richmond' => { short: 'ric', url: 'http://richmond.craigslist.org' },
    'Richmond' => { short: 'rin', url: 'http://richmondin.craigslist.org' },
    'Rio de Janeiro' => { short: 'rio', url: 'http://rio.craigslist.org' },
    'Reykjavik' => { short: 'rkv', url: 'http://reykjavik.craigslist.org' },
    'Rochester' => { short: 'rmn', url: 'http://rmn.craigslist.org' },
    'Reno / Tahoe' => { short: 'rno', url: 'http://reno.craigslist.org' },
    'Brittany' => { short: 'rns', url: 'http://rennes.craigslist.org' },
    'Roanoke' => { short: 'roa', url: 'http://roanoke.craigslist.org' },
    'Rome' => { short: 'rom', url: 'http://rome.craigslist.it' },
    'Normandy' => { short: 'rou', url: 'http://rouen.craigslist.org' },
    'Roswell / Carlsbad' => { short: 'row', url: 'http://roswell.craigslist.org' },
    'Sacramento' => { short: 'sac', url: 'http://sacramento.craigslist.org' },
    'Santa Fe / Taos' => { short: 'saf', url: 'http://santafe.craigslist.org' },
    'El Salvador' => { short: 'sal', url: 'http://elsalvador.craigslist.org' },
    'San Antonio' => { short: 'sat', url: 'http://sanantonio.craigslist.org' },
    'Savannah / Hinesville' => { short: 'sav', url: 'http://savannah.craigslist.org' },
    'Santa Barbara' => { short: 'sba', url: 'http://santabarbara.craigslist.org' },
    'Sheboygan' => { short: 'sbm', url: 'http://sheboygan.craigslist.org' },
    'South Bend / Michiana' => { short: 'sbn', url: 'http://southbend.craigslist.org' },
    'Chile' => { short: 'scl', url: 'http://santiago.craigslist.org' },
    'Sendai' => { short: 'sdj', url: 'http://sendai.craigslist.jp' },
    'South Dakota' => { short: 'sdk', url: 'http://sd.craigslist.org' },
    'San Diego' => { short: 'sdo', url: 'http://sandiego.craigslist.org' },
    'Dominican Republic' => { short: 'sdq', url: 'http://santodomingo.craigslist.org' },
    'Seattle-Tacoma' => { short: 'sea', url: 'http://seattle.craigslist.org' },
    'Southeast KS' => { short: 'sek', url: 'http://seks.craigslist.org' },
    'Seoul' => { short: 'sel', url: 'http://seoul.craigslist.co.kr' },
    'Sevilla' => { short: 'sev', url: 'http://sevilla.craigslist.es' },
    'San Francisco Bay Area' => { short: 'sfo', url: 'http://sfbay.craigslist.org' },
    'Springfield' => { short: 'sgf', url: 'http://springfield.craigslist.org' },
    'Saguenay' => { short: 'sgy', url: 'http://saguenay.craigslist.ca' },
    'Shanghai' => { short: 'sha', url: 'http://shanghai.craigslist.com.cn' },
    'Sherbrooke' => { short: 'shb', url: 'http://sherbrooke.craigslist.ca' },
    'Harrisonburg' => { short: 'shd', url: 'http://harrisonburg.craigslist.org' },
    'Shenyang' => { short: 'she', url: 'http://shenyang.craigslist.com.cn' },
    'Sheffield' => { short: 'shf', url: 'http://sheffield.craigslist.co.uk' },
    'Shreveport' => { short: 'shv', url: 'http://shreveport.craigslist.org' },
    'Sicilia' => { short: 'sic', url: 'http://sicily.craigslist.it' },
    'San Angelo' => { short: 'sjt', url: 'http://sanangelo.craigslist.org' },
    'Skeena-Bulkley' => { short: 'ske', url: 'http://skeena.craigslist.ca' },
    'Saskatoon' => { short: 'skt', url: 'http://saskatoon.craigslist.ca' },
    'Sandusky' => { short: 'sky', url: 'http://sandusky.craigslist.org' },
    'Salt Lake City' => { short: 'slc', url: 'http://saltlakecity.craigslist.org' },
    'Salem' => { short: 'sle', url: 'http://salem.craigslist.org' },
    'San Luis Obispo' => { short: 'slo', url: 'http://slo.craigslist.org' },
    'South Coast' => { short: 'sma', url: 'http://southcoast.craigslist.org' },
    'Southern Maryland' => { short: 'smd', url: 'http://smd.craigslist.org' },
    'Southeast Missouri' => { short: 'smo', url: 'http://semo.craigslist.org' },
    'Santa Maria' => { short: 'smx', url: 'http://santamaria.craigslist.org' },
    'Singapore' => { short: 'sng', url: 'http://singapore.craigslist.com.sg' },
    'South Jersey' => { short: 'snj', url: 'http://southjersey.craigslist.org' },
    'Salina' => { short: 'sns', url: 'http://salina.craigslist.org' },
    'Bulgaria' => { short: 'sof', url: 'http://bulgaria.craigslist.org' },
    'Sault Ste Marie' => { short: 'soo', url: 'http://soo.craigslist.ca' },
    'Hampshire' => { short: 'sou', url: 'http://hampshire.craigslist.co.uk' },
    'Show Low' => { short: 'sow', url: 'http://showlow.craigslist.org' },
    'Springfield' => { short: 'spi', url: 'http://springfieldil.craigslist.org' },
    'Spokane / Coeur d\'Alene' => { short: 'spk', url: 'http://spokane.craigslist.org' },
    'Sao Paulo' => { short: 'spo', url: 'http://saopaulo.craigslist.org' },
    'Sapporo' => { short: 'spp', url: 'http://sapporo.craigslist.jp' },
    'Sardinia' => { short: 'srd', url: 'http://sardinia.craigslist.it' },
    'Sarnia' => { short: 'srn', url: 'http://sarnia.craigslist.ca' },
    'Sarasota- Radenton' => { short: 'srq', url: 'http://sarasota.craigslist.org' },
    'Salvador, Ahia' => { short: 'ssa', url: 'http://salvador.craigslist.org' },
    'Siskiyou County' => { short: 'ssk', url: 'http://siskiyou.craigslist.org' },
    'Susanville' => { short: 'ssn', url: 'http://susanville.craigslist.org' },
    'St Cloud' => { short: 'stc', url: 'http://stcloud.craigslist.org' },
    'St George' => { short: 'stg', url: 'http://stgeorge.craigslist.org' },
    'Sweden' => { short: 'sth', url: 'http://stockholm.craigslist.se' },
    'St Joseph' => { short: 'stj', url: 'http://stjoseph.craigslist.org' },
    'Stockton' => { short: 'stk', url: 'http://stockton.craigslist.org' },
    'St Louis' => { short: 'stl', url: 'http://stlouis.craigslist.org' },
    'St Petersburg' => { short: 'stp', url: 'http://stpetersburg.craigslist.org' },
    'Stuttgart' => { short: 'str', url: 'http://stuttgart.craigslist.de' },
    'Sudbury' => { short: 'sud', url: 'http://sudbury.craigslist.ca' },
    'Sunshine Coast' => { short: 'sun', url: 'http://sunshine.craigslist.ca' },
    'Sioux City' => { short: 'sux', url: 'http://siouxcity.craigslist.org' },
    'Surat Surat' => { short: 'svt', url: 'http://surat.craigslist.co.in' },
    'Southwest KS' => { short: 'swk', url: 'http://swks.craigslist.org' },
    'Southwest Michigan' => { short: 'swm', url: 'http://swmi.craigslist.org' },
    'Southern WV' => { short: 'swv', url: 'http://swv.craigslist.org' },
    'Strasbourg' => { short: 'sxb', url: 'http://strasbourg.craigslist.org' },
    'Sydney' => { short: 'syd', url: 'http://sydney.craigslist.com.au' },
    'Syracuse' => { short: 'syr', url: 'http://syracuse.craigslist.org' },
    'Shenzhen' => { short: 'szx', url: 'http://shenzhen.craigslist.com.cn' },
    'Tallahassee' => { short: 'tal', url: 'http://tallahassee.craigslist.org' },
    'Statesboro' => { short: 'tbr', url: 'http://statesboro.craigslist.org' },
    'Thunder Bay' => { short: 'tby', url: 'http://thunderbay.craigslist.ca' },
    'Canarias' => { short: 'tfn', url: 'http://canarias.craigslist.es' },
    'Terre Haute' => { short: 'tha', url: 'http://terrehaute.craigslist.org' },
    'The Thumb' => { short: 'thb', url: 'http://thumb.craigslist.org' },
    'Tijuana' => { short: 'tij', url: 'http://tijuana.craigslist.com.mx' },
    'Toulouse' => { short: 'tls', url: 'http://toulouse.craigslist.org' },
    'Tel Aviv' => { short: 'tlv', url: 'http://telaviv.craigslist.org' },
    'Territories' => { short: 'toc', url: 'http://territories.craigslist.ca' },
    'Tokyo' => { short: 'tok', url: 'http://tokyo.craigslist.jp' },
    'Toledo' => { short: 'tol', url: 'http://toledo.craigslist.org' },
    'Toronto' => { short: 'tor', url: 'http://toronto.craigslist.ca' },
    'Tampa Bay Area' => { short: 'tpa', url: 'http://tampa.craigslist.org' },
    'Topeka' => { short: 'tpk', url: 'http://topeka.craigslist.org' },
    'Iran' => { short: 'trh', url: 'http://tehran.craigslist.org' },
    'Tri-Cities' => { short: 'tri', url: 'http://tricities.craigslist.org' },
    'Torino' => { short: 'trn', url: 'http://torino.craigslist.it' },
    'Trois-Rivieres' => { short: 'trs', url: 'http://troisrivieres.craigslist.ca' },
    'Tuscaloosa' => { short: 'tsc', url: 'http://tuscaloosa.craigslist.org' },
    'San Marcos' => { short: 'tsu', url: 'http://sanmarcos.craigslist.org' },
    'Twin Tiers NY/PA' => { short: 'tts', url: 'http://twintiers.craigslist.org' },
    'Tulsa' => { short: 'tul', url: 'http://tulsa.craigslist.org' },
    'Tunisia' => { short: 'tun', url: 'http://tunis.craigslist.org' },
    'Tucson' => { short: 'tus', url: 'http://tucson.craigslist.org' },
    'Taiwan' => { short: 'twd', url: 'http://taipei.craigslist.com.tw' },
    'Twin Falls' => { short: 'twf', url: 'http://twinfalls.craigslist.org' },
    'Texarkana' => { short: 'txk', url: 'http://texarkana.craigslist.org' },
    'Texoma' => { short: 'txm', url: 'http://texoma.craigslist.org' },
    'United Arab Emirates' => { short: 'uae', url: 'http://dubai.craigslist.org' },
    'Hattiesburg' => { short: 'usm', url: 'http://hattiesburg.craigslist.org' },
    'St Augustine' => { short: 'ust', url: 'http://staugustine.craigslist.org' },
    'Utica-Rome-Oneida' => { short: 'uti', url: 'http://utica.craigslist.org' },
    'Charlottesville' => { short: 'uva', url: 'http://charlottesville.craigslist.org' },
    'Valencia' => { short: 'val', url: 'http://valencia.craigslist.es' },
    'Vancouver' => { short: 'van', url: 'http://vancouver.craigslist.ca' },
    'Southwest VA' => { short: 'vaw', url: 'http://swva.craigslist.org' },
    'Venice / Veneto' => { short: 'vce', url: 'http://venice.craigslist.it' },
    'Veracruz' => { short: 'vcz', url: 'http://veracruz.craigslist.com.mx' },
    'Victoria' => { short: 'vic', url: 'http://victoria.craigslist.ca' },
    'Vienna' => { short: 'vie', url: 'http://vienna.craigslist.at' },
    'Visalia-Tulare' => { short: 'vis', url: 'http://visalia.craigslist.org' },
    'Valdosta' => { short: 'vld', url: 'http://valdosta.craigslist.org' },
    'New River Valley' => { short: 'vpi', url: 'http://blacksburg.craigslist.org' },
    'U.S. Virgin Islands' => { short: 'vrg', url: 'http://virgin.craigslist.org' },
    'Virgin Islands' => { short: 'vrg', url: 'http://virgin.craigslist.org' },
    'Vietnam' => { short: 'vtn', url: 'http://vietnam.craigslist.org' },
    'Victoria' => { short: 'vtx', url: 'http://victoriatx.craigslist.org' },
    'Wausau' => { short: 'wau', url: 'http://wausau.craigslist.org' },
    'Poland' => { short: 'waw', url: 'http://warsaw.craigslist.pl' },
    'Waco' => { short: 'wco', url: 'http://waco.craigslist.org' },
    'Washington' => { short: 'wdc', url: 'http://washingtondc.craigslist.org' },
    'Wenatchee' => { short: 'wen', url: 'http://wenatchee.craigslist.org' },
    'Whitehorse' => { short: 'whh', url: 'http://whitehorse.craigslist.ca' },
    'Whistler' => { short: 'whi', url: 'http://whistler.craigslist.ca' },
    'Northern Panhandle' => { short: 'whl', url: 'http://wheeling.craigslist.org' },
    'Wichita' => { short: 'wic', url: 'http://wichita.craigslist.org' },
    'Winnipeg' => { short: 'win', url: 'http://winnipeg.craigslist.ca' },
    'Western KY' => { short: 'wky', url: 'http://westky.craigslist.org' },
    'Wellington' => { short: 'wll', url: 'http://wellington.craigslist.org' },
    'Waterloo / Cedar Falls' => { short: 'wlo', url: 'http://waterloo.craigslist.org' },
    'Western Massachusetts' => { short: 'wma', url: 'http://westernmass.craigslist.org' },
    'Western Maryland' => { short: 'wmd', url: 'http://westmd.craigslist.org' },
    'Wilmington' => { short: 'wnc', url: 'http://wilmington.craigslist.org' },
    'Bicol Region' => { short: 'wnp', url: 'http://naga.craigslist.com.ph' },
    'Wollongong' => { short: 'wol', url: 'http://wollongong.craigslist.com.au' },
    'Worcester / Central MA' => { short: 'wor', url: 'http://worcester.craigslist.org' },
    'Williamsport' => { short: 'wpt', url: 'http://williamsport.craigslist.org' },
    'Winston-Salem' => { short: 'wsl', url: 'http://winstonsalem.craigslist.org' },
    'Windsor' => { short: 'wsr', url: 'http://windsor.craigslist.ca' },
    'Wichita Falls' => { short: 'wtf', url: 'http://wichitafalls.craigslist.org' },
    'Watertown' => { short: 'wtn', url: 'http://watertown.craigslist.org' },
    'Southwest TX' => { short: 'wtx', url: 'http://bigbend.craigslist.org' },
    'Wuhan' => { short: 'wuh', url: 'http://wuhan.craigslist.com.cn' },
    'West Virginia (Old)' => { short: 'wva', url: 'http://wv.craigslist.org' },
    'Morgantown' => { short: 'wvu', url: 'http://morgantown.craigslist.org' },
    'Wyoming' => { short: 'wyo', url: 'http://wyoming.craigslist.org' },
    'Xi\'an' => { short: 'xiy', url: 'http://xian.craigslist.com.cn' },
    'Yakima' => { short: 'yak', url: 'http://yakima.craigslist.org' },
    'Yellowknife' => { short: 'ykf', url: 'http://yellowknife.craigslist.ca' },
    'Youngstown' => { short: 'yng', url: 'http://youngstown.craigslist.org' },
    'Peterborough' => { short: 'ypq', url: 'http://peterborough.craigslist.ca' },
    'Okaloosa / Walton' => { short: 'yps', url: 'http://okaloosa.craigslist.org' },
    'York' => { short: 'yrk', url: 'http://york.craigslist.org' },
    'Yucatan' => { short: 'yuc', url: 'http://yucatan.craigslist.com.mx' },
    'Yuma' => { short: 'yum', url: 'http://yuma.craigslist.org' },
    'Upper Peninsula' => { short: 'yup', url: 'http://up.craigslist.org' },
    'Prince George' => { short: 'yxs', url: 'http://princegeorge.craigslist.ca' },
    'Croatia' => { short: 'zag', url: 'http://zagreb.craigslist.org' },
    'Zamboanga' => { short: 'zam', url: 'http://zamboanga.craigslist.com.ph' },
    'Zurich' => { short: 'zur', url: 'http://zurich.craigslist.ch' },
    'Zanesville / Cambridge' => { short: 'zyl', url: 'http://zanesville.craigslist.org' }
      }

    CATEGORIES = {
      community: {
        path: 'ccc',
        children: {
          activities: 'act',
          artists: 'ats',
          childcare: 'kid',
          general: 'com',
          groups: 'grp',
          pets: 'pet',
          events: 'eve',
          lost_found: 'laf',
          musicians: 'muc',
          local_news: 'vnn',
          politics: 'pol',
          rideshare: 'rid',
          volunteers: 'vol',
          classes: 'cls'
        }
      },
      housing: {
        path: 'hhh',
        children: {
          apts_housing: 'apa',
          rooms_shared: 'roo',
          sublets_temporary: 'sub',
          housing_wanted: 'hsw',
          housing_swap: 'swp',
          vacation_rentals: 'vac',
          parking_storage: 'prk',
          office_commercial: 'off',
          real_estate_for_sale: 'rea'
        }
      },
      for_sale: {
        path: 'sss',
        children: {
          appliances: 'ppa',
          antiques: 'ata',
          barter: 'bar',
          bikes: 'bia',
          boats: 'boo',
          books: 'bka',
          business: 'bfa',
          computer: 'sya',
          free: 'zip',
          furniture: 'fua',
          general: 'foa',
          jewelry: 'jwa',
          materials: 'maa',
          rvs: 'rva',
          sporting: 'sga',
          tickets: 'tia',
          tools: 'tla',
          wanted: 'wan',
          arts_crafts: 'ara',
          auto_parts: 'pta',
          baby_kids: 'baa',
          beauty_hlth: 'haa',
          cars_trucks: 'i/autos',
          cds_dvd_vhs: 'ema',
          cell_phones: 'moa',
          clothes_acc: 'cla',
          collectibles: 'cba',
          electronics: 'ela',
          farm_garden: 'gra',
          garage_sale: 'gms',
          household: 'hsa',
          motorcycles: 'mca',
          music_instr: 'msa',
          photo_video: 'pha',
          toys_games: 'taa',
          video_gaming: 'vga'
        }
      },
      services: {
        path: 'bbb',
        children: {
          beauty: 'brs',
          creative: 'crs',
          computer: 'cps',
          cycle: 'cys',
          event: 'evs',
          financial: 'fns',
          legal: 'lgs',
          lessons: 'lss',
          marine: 'mas',
          pet: 'pas',
          automotive: 'aos',
          farm_garden: 'fgs',
          household: 'hss',
          labor_move: 'lbs',
          skilld_trade: 'sks',
          real_estate: 'rts',
          sm_biz_ads: 'biz',
          therapeutic: 'thp',
          travel_vac: 'trv',
          write_ed_tr8: 'wet'
        }
      },
      jobs: {
        path: 'jjj',
        children: {
          accounting_finance: 'acc',
          admin_office: 'ofc',
          arch_engineering: 'egr',
          art_media_design: 'med',
          biotech_science: 'sci',
          business_mgmt: 'bus',
          customer_service: 'csr',
          education: 'edu',
          food_bev_hosp: 'fbh',
          general_labor: 'lab',
          government: 'gov',
          human_resources: 'hum',
          internet_engineers: 'eng',
          legal_paralegal: 'lgl',
          manufacturing: 'mnu',
          marketing_pr_ad: 'mar',
          medical_health: 'hea',
          nonprofit_sector: 'npo',
          real_estate: 'rej',
          retail_wholesale: 'ret',
          sales_biz_dev: 'sls',
          salon_spa_fitness: 'spa',
          security: 'sec',
          skilled_trade_craft: 'trd',
          software_qa_dba: 'sof',
          systems_network: 'sad',
          technical_support: 'tch',
          transport: 'trp',
          tv_film_video: 'tfr',
          web_info_design: 'web',
          writing_editing: 'wri',
          etc: 'etc'
        }
      },
      gigs: {
        path: 'ggg',
        children: {
          crew: 'cwg',
          event: 'evg',
          labor: 'lbg',
          talent: 'tlg',
          computer: 'cpg',
          creative: 'crg',
          domestic: 'dmg',
          writing: 'wrg'
        }
      },
      resumes: {
        path: 'res'
      }
    }
end
